In [23]:
#Generating a 3X4 NumPy array with random integers between 1 and 50
import numpy as np
arr1 = np.random.randint(0,50,size=(3,4))
print("New array of random integers: ")
print(arr1)

New array of random integers: 
[[23 23  2 39]
 [24 36  6  5]
 [38 12 24 40]]


In [31]:
#mean
print("Mean is: ", arr1.mean())
#Median
print("Median is: ", np.median(arr1))
#Standard Deviation
print("Standard deviation is: ", arr1.std())

Mean is:  22.666666666666668
Median is:  23.5
Standard deviation is:  13.274871834493252


In [47]:
#sum of all elements:
print("Sum of all elements is: ", arr1.sum())
#sum of each row:
row_sums = arr1.sum(axis=1)
a=1
for i in row_sums:
    print(f"Sum of {a} row is: ", i)
    a+=1;

Sum of all elements is:  272
Sum of 1 row is:  87
Sum of 2 row is:  71
Sum of 3 row is:  114


In [53]:
#reshape
print("After reshaping to 2 X 6, array is: ", arr1.reshape(2,6))

After reshaping to 2 X 6, array is:  [[23 23  2 39 24 36]
 [ 6  5 38 12 24 40]]


In [79]:
import numpy as np


arr1 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])


print("Sum:\n", arr1 + arr2)


Sum:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]


In [81]:
import numpy as np


arr1 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])


print("Difference:\n", arr1 - arr2)

Difference:
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [83]:
import numpy as np


arr1 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])


print("Product is:\n", np.dot(arr1,arr2))

Product is:
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [85]:
print("Transpose of array 1: ", arr1.T)
print("Transpose of array 2: ", arr2.T)

Transpose of array 1:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of array 2:  [[10 13 16]
 [11 14 17]
 [12 15 18]]


In [98]:
det = np.linalg.det(arr1)
print("determinant is: ", det)

if det!=0 :
    print("inverse is: ", np.linalg.inv(arr1))
else:
    print("Matrix is not invertible")

determinant is:  6.66133814775094e-16
inverse is:  [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
